"""Add Freebie table and relationships

Revision ID: 9535e20f4604
Revises: 269ceecc94e5
Create Date: 2025-05-26 11:32:30.954558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9535e20f4604'
down_revision = '269ceecc94e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('freebies', schema=None) as batch_op:
        batch_op.alter_column('item_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('value',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('dev_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('freebies', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('dev_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('value',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('item_name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
